//@flow

export const mistTypes = {
    IDENTITIES: "IDENTITIES",
    OWN_IDENTITY: "OWN_IDENTITY",
    PEERS: "PEERS",
    ADD_MODEL: "ADD_MODEL",
    REMOVE_MODEL: "REMOVE_MODEL",
    UPDATE_ENDPOINT: "UPDATE_ENDPOINT",
    REMOVE_ENDPOINT: "REMOVE_ENDPOINT"
}